name: Gradle Build Action

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Publish test results
        id: publish-test-results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          publish: true
          footer: <table><tr><th><th>Tests</th><th>Passed ✅</th><th>Skipped ⏭️</th><th>Failed ❌</th></tr><tr><td>JUnit Test Report</td><td>${{ steps.publish-test-results.outputs.total }} ran</td><td>${{ steps.publish-test-results.outputs.passed }} passed</td><td>${{ steps.publish-test-results.outputs.skipped }} skipped</td><td>${{ steps.publish-test-results.outputs.failed }} failed</td></tr></table>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release-drafter.outputs.upload_url }}
          asset_path: ./build/libs/Hanamizuki-1.0-SNAPSHOT-all.jar
          asset_name: Hanamizuki_${{ steps.release-drafter.outputs.tag_name }}.jar
          asset_content_type: application/jar
